# Generated by Django 2.1.1 on 2020-10-13 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20201013_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_of_owning', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
