# Generated by Django 2.1.1 on 2020-12-04 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        ('accounts', '0001_initial'),
        ('school_class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherContentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_class.ClassModel')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.SubjectModel')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pay', models.IntegerField()),
                ('leaves', models.IntegerField()),
                ('date_joining', models.DateTimeField(auto_now_add=True)),
                ('subjects', models.ManyToManyField(blank=True, null=True, to='subject.SubjectModel')),
            ],
        ),
    ]
