# Generated by Django 2.1.1 on 2020-11-09 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pay', models.IntegerField()),
                ('leaves', models.IntegerField()),
                ('date_joining', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
