# Generated by Django 2.1.1 on 2020-11-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teachercontentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachercontentmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='teachercontentmodel',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachercontentmodel',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='teachercontentmodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
