# Generated by Django 2.1.1 on 2020-11-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('teacher', '0004_auto_20201110_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='subject.SubjectModel'),
        ),
    ]
