# Generated by Django 2.1.1 on 2020-11-23 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0002_sectionmodel_subjects'),
        ('subject', '0002_remove_subjectmodel_section'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lecture_file', models.FileField(max_length=254, upload_to='lecture/')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.SectionModel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.SubjectModel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherModel')),
            ],
        ),
    ]
