# Generated by Django 2.1.1 on 2020-11-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturemodel',
            name='lecture_file',
            field=models.FileField(blank=True, null=True, upload_to='teacher/lectures'),
        ),
    ]
