# Generated by Django 2.1.1 on 2020-11-23 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0002_sectionmodel_subjects'),
        ('teacher', '0001_initial'),
        ('student', '0003_auto_20201118_0555'),
        ('subject', '0002_remove_subjectmodel_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentQuizPaperModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('which_type', models.CharField(choices=[('Assignment', 'Assignment'), ('Quiz', 'Quiz'), ('Paper', 'Paper')], default='Assignment', max_length=10)),
                ('assignment_file', models.FileField(upload_to='teacher/assignment/')),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('total_marks', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.SectionModel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.SubjectModel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherModel')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FileField(upload_to='student/assignment/')),
                ('marks_obtained', models.IntegerField()),
                ('marked', models.BooleanField(default=False)),
                ('remarks', models.CharField(max_length=500)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqp.AssignmentQuizPaperModel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentModel')),
            ],
        ),
    ]
