# Generated by Django 2.1.1 on 2020-11-09 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0001_initial'),
        ('teacher', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('assignment_file', models.CharField(max_length=300)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('total_marks', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.SectionModel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.SubjectModel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherModel')),
            ],
        ),
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_marks', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.SectionModel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.SubjectModel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherModel')),
            ],
        ),
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_marks', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.SectionModel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.SubjectModel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherModel')),
            ],
        ),
    ]
