# Generated by Django 2.1.1 on 2020-11-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AQP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammodel',
            name='file',
        ),
        migrations.AddField(
            model_name='exammodel',
            name='exam_file',
            field=models.FileField(blank=True, null=True, upload_to='teacher/exams'),
        ),
        migrations.AlterField(
            model_name='assignmentmodel',
            name='assignment_file',
            field=models.FileField(blank=True, null=True, upload_to='teacher/assignments'),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='teacher/quiz'),
        ),
    ]
