# Generated by Django 2.1.1 on 2020-11-09 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        ('school_class', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=5)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_class.ClassModel')),
                ('subjects', models.ManyToManyField(to='subject.SubjectModel')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherModel')),
            ],
        ),
    ]
