# Generated by Django 2.1.1 on 2020-11-19 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionmodel',
            old_name='teacher',
            new_name='class_teacher',
        ),
    ]
