# Generated by Django 2.1.1 on 2020-10-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_remove_subjectmodel_section'),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionmodel',
            name='subjects',
            field=models.ManyToManyField(to='subject.SubjectModel'),
        ),
    ]
