# Generated by Django 2.1.1 on 2020-11-09 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0001_initial'),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.OwnerModel')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.PrincipalModel')),
            ],
        ),
    ]
