# Generated by Django 2.1.1 on 2020-10-15 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolmodel',
            old_name='school_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='schoolmodel',
            old_name='school_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='schoolmodel',
            old_name='school_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='schoolmodel',
            name='school_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
