# Generated by Django 2.1.1 on 2020-10-26 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20201026_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmodel',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='owner.OwnerModel'),
        ),
        migrations.AlterField(
            model_name='schoolmodel',
            name='principal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='principal.PrincipalModel'),
        ),
    ]
