# Generated by Django 2.1.1 on 2020-10-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20201026_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmodel',
            name='school_id',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
