# Generated by Django 2.1.1 on 2020-10-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201013_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principal',
            name='user',
        ),
        migrations.DeleteModel(
            name='Principal',
        ),
    ]
