# Generated by Django 2.1.1 on 2020-11-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboardmodel',
            name='notice_file',
            field=models.CharField(max_length=1000),
        ),
    ]
