# Generated by Django 2.1.1 on 2020-11-25 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0002_auto_20201125_0525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticeboardmodel',
            old_name='notice_file',
            new_name='notice',
        ),
    ]
