# Generated by Django 2.1.1 on 2020-12-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0004_auto_20201126_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoardChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='noticeboardmodel',
            name='user_group',
        ),
        migrations.AddField(
            model_name='noticeboardmodel',
            name='user_group',
            field=models.ManyToManyField(to='noticeboard.NoticeBoardChoices'),
        ),
    ]
