# Generated by Django 2.1.1 on 2020-12-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0005_auto_20201207_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboardmodel',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
