# Generated by Django 2.1.1 on 2020-12-07 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0006_noticeboardmodel_is_approve'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoticeBoardChoices',
            new_name='NoticeBoardChoice',
        ),
    ]
