# Generated by Django 2.1.1 on 2020-12-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0007_auto_20201207_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboardmodel',
            name='notice',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='noticeboardmodel',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
