# Generated by Django 2.1.1 on 2020-12-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0008_auto_20201207_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboardmodel',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
