# Generated by Django 2.1.1 on 2020-12-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0009_auto_20201207_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticeboardmodel',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='noticeboardmodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
