# Generated by Django 2.1.1 on 2020-12-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queriesmodel',
            name='status',
            field=models.CharField(choices=[('Question', 'Question'), ('Response', 'Response')], default='Question', max_length=10),
        ),
    ]
