# Generated by Django 2.1.1 on 2020-12-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_queriesmodel_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='queriesmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='queries/'),
        ),
    ]
