# Generated by Django 2.1.1 on 2020-12-04 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('qualification', models.CharField(max_length=500, null=True)),
                ('pay', models.IntegerField(null=True)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
