# Generated by Django 2.1.1 on 2020-10-14 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20201014_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('qualification', models.CharField(max_length=500)),
                ('pay', models.IntegerField()),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
