# Generated by Django 2.1.1 on 2020-10-14 06:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Principal',
            new_name='PrincipalModel',
        ),
    ]
