# Generated by Django 2.1.1 on 2020-10-15 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.SectionModel')),
            ],
        ),
    ]
